[font]
normal = { family = "HackGen Console NF" }
size = 12.5

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
opacity = 1

[terminal]
osc52 = "CopyPaste"
