return {
  "Shougo/ddu.vim",
  dependencies = {
    "vim-denops/denops.vim",
    "lambdalisue/kensaku.vim",
    "Shougo/ddu-commands.vim",
    -- column
    "Shougo/ddu-column-filename",
    "tamago3keran/ddu-column-devicon_filename",
    -- filter
    "Milly/ddu-filter-kensaku",
    "Shougo/ddu-filter-matcher_files",
    "Shougo/ddu-filter-matcher_relative",
    "Shougo/ddu-filter-matcher_substring",
    "Shougo/ddu-filter-sorter_alpha",
    "Shougo/ddu-filter-sorter_reversed",
    "kamecha/ddu-filter-converter_file_icon",
    "kamecha/ddu-filter-converter_file_info",
    "uga-rosa/ddu-filter-converter_devicon",
    -- kind
    "Shougo/ddu-kind-file",
    "Shougo/ddu-kind-word",
    -- source
    "4513ECHO/ddu-source-emoji",
    -- "Milly/windows-clipboard-history.vim",
    "Shougo/ddu-source-dummy",
    "Shougo/ddu-source-file",
    "Shougo/ddu-source-file_old",
    "Shougo/ddu-source-file_rec",
    "Shougo/ddu-source-line",
    "kuuote/ddu-source-git_diff",
    "kuuote/ddu-source-git_status",
    "kuuote/ddu-source-mr",
    "kyoh86/ddu-source-command",
    "kyoh86/ddu-source-git_branch",
    "kyoh86/ddu-source-git_diff_tree",
    "kyoh86/ddu-source-git_log",
    "kyoh86/ddu-source-lazy_nvim",
    "matsui54/ddu-source-command_history",
    "matsui54/ddu-source-help",
    "peacock0803sz/ddu-source-git_stash",
    "shun/ddu-source-buffer",
    "shun/ddu-source-rg",
    "uga-rosa/ddu-source-lsp",
    "uga-rosa/ddu-source-search_history",
    -- ui
    "Shougo/ddu-ui-ff",
    "Shougo/ddu-ui-filer",
  },
}
