---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.156.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: BurntSushi/ripgrep@14.1.0
- name: biomejs/biome@cli/v1.6.3
- name: cli/cli@v2.46.0
- name: dandavison/delta@0.17.0
- name: denoland/deno@v1.42.1
- name: docker/cli@v26.0.0
- name: dylanaraps/neofetch@7.1.0
- name: github/hub@v2.14.2
- name: golang/go@go1.22.1
- name: moonrepo/proto@v0.32.1
- name: sharkdp/bat@v0.24.0
- name: ziglang/zig@0.11.0
- name: JohnnyMorganz/StyLua@v0.20.0
- name: LuaLS/lua-language-server@3.7.4
- name: rust-lang/rust-analyzer@2024-04-01
- name: x-motemen/ghq@v1.5.0
- name: eza-community/eza@v0.18.9
- name: peco/peco@v0.5.11
- name: jqlang/jq@jq-1.7.1
- name: jdx/mise@v2024.4.0
