# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.283.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: BurntSushi/ripgrep@14.1.1
  - name: LuaLS/lua-language-server@3.13.5
  - name: cli/cli@v2.64.0
  - name: dandavison/delta@0.18.2
  - name: docker/cli@v27.4.1
  - name: dylanaraps/neofetch@7.1.0
  - name: eza-community/eza@v0.20.13
  - name: github/hub@v2.14.2
  - name: golang/go@go1.23.4
  - name: jdx/mise@v2024.12.19
  - name: jqlang/jq@jq-1.7.1
  - name: peco/peco@v0.5.11
  - name: sharkdp/bat@v0.24.0
  - name: x-motemen/ghq@v1.7.1
  - name: ziglang/zig@0.13.0
  - name: docker/compose@v2.32.1
  - name: jesseduffield/lazydocker@v0.24.1
  - name: jesseduffield/lazygit@v0.44.1
