---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.206.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: BurntSushi/ripgrep@14.1.0
- name: LuaLS/lua-language-server@3.9.3
- name: biomejs/biome@cli/v1.8.3
- name: cli/cli@v2.53.0
- name: dandavison/delta@0.17.0
- name: docker/cli@v27.0.3
- name: dylanaraps/neofetch@7.1.0
- name: eza-community/eza@v0.18.22
- name: github/hub@v2.14.2
- name: golang/go@go1.22.5
- name: jdx/mise@v2024.7.4
- name: jqlang/jq@jq-1.7.1
- name: peco/peco@v0.5.11
- name: sharkdp/bat@v0.24.0
- name: x-motemen/ghq@v1.6.2
- name: ziglang/zig@0.13.0
- name: docker/compose@v2.29.0
- name: jesseduffield/lazydocker@v0.23.3
- name: jesseduffield/lazygit@v0.43.1
