---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.188.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: BurntSushi/ripgrep@14.1.0
- name: LuaLS/lua-language-server@3.9.1
- name: biomejs/biome@cli/v1.7.3
- name: cli/cli@v2.50.0
- name: dandavison/delta@0.17.0
- name: docker/cli@v26.1.3
- name: dylanaraps/neofetch@7.1.0
- name: eza-community/eza@v0.18.16
- name: github/hub@v2.14.2
- name: golang/go@go1.22.3
- name: jdx/mise@v2024.6.0
- name: jqlang/jq@jq-1.7.1
- name: peco/peco@v0.5.11
- name: rhysd/vim-startuptime@v1.3.2
- name: sharkdp/bat@v0.24.0
- name: x-motemen/ghq@v1.6.1
- name: ziglang/zig@0.12.0
