---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.152.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: BurntSushi/ripgrep@14.1.0
- name: biomejs/biome@cli/v1.6.0
- name: cli/cli@v2.45.0
- name: dandavison/delta@0.16.5
- name: denoland/deno@v1.41.3
- name: docker/cli@v25.0.4
- name: dylanaraps/neofetch@7.1.0
- name: github/hub@v2.14.2
- name: golang/go@go1.22.1
- name: moonrepo/proto@v0.31.5
- name: sharkdp/bat@v0.24.0
- name: ziglang/zig@0.11.0
- name: JohnnyMorganz/StyLua@v0.20.0
- name: LuaLS/lua-language-server@3.7.4
- name: rust-lang/rust-analyzer@2024-03-11
- name: x-motemen/ghq@v1.5.0
- name: eza-community/eza@v0.18.7
- name: peco/peco@v0.5.11
- name: jqlang/jq@jq-1.7.1
