[[plugins]]
repo='https://github.com/nvimdev/guard.nvim'
depends=['guard-collection']
lua_source='''
local ft = require('guard.filetype')
ft(
    'javascript,javascriptreact,typescript,typescriptreact,vue,css,scss,less,html,json,jsonc,yaml,markdown,markdown.mdx,graphql,handlebars'
  )
  :fmt({
    cmd = 'deno',
    args = { 'fmt', '-' },
    stdin = true,
  })

ft('go'):fmt('gofmt')

local stylua = vim.fs.joinpath(vim.fn.stdpath('data'), 'mason', 'packages', 'stylua', 'stylua.exe')
ft('lua'):fmt {
  cmd = stylua,
  args = { '-' },
  stdin = true,
}

require('guard').setup {
  fmt_on_save = false,
  lsp_as_default_formatter = false,
}

vim.keymap.set({ 'n' }, 'mf', function()
  vim.cmd([[GuardFmt]])
end, { desc = 'format file' })
'''

[[plugins]]
repo='https://github.com/nvimdev/guard-collection'
