[[plugins]]
repo='https://github.com/EdenEast/nightfox.nvim'

[[plugins]]
repo='https://github.com/bluz71/vim-nightfly-colors'

[[plugins]]
repo='https://github.com/zootedb0t/citruszest.nvim'

[[plugins]]
repo='https://github.com/arrow2nd/aqua'
