[[plugins]]
repo='https://github.com/Shougo/ddc.vim'
depends = 'denops.vim'
on_event = 'InsertEnter'
hooks_file='~\dotfiles\config\nvim\rc\ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/pum.vim'
hook_source = '''
  call pum#set_option(#{
    \   auto_confirm_time: 3000,
    \   auto_select: v:false,
    \   border: 'none',
    \   follow_cursor: v:false,
    \   highlight_scrollbar: 'None',
    \   horizontal_menu: v:false,
    \   max_width: 80,
    \   offset_cmdcol: 0,
    \   padding: v:false,
    \   preview: v:true,
    \   preview_width: 80,
    \   reversed: v:false,
    \   use_complete: v:true,
    \   use_setline: v:false,
    \ })

  call pum#set_local_option('c', #{
    \   horizontal_menu: v:false,
    \ })

  autocmd FileType ddu-ff-filter
    \ call pum#set_buffer_option(#{
    \   direction: 'above',
    \ })
'''

[[plugins]]
repo='https://github.com/Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-ui-none'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-codeium'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-input'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-rg'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-line'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-omni'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-source-rtags'
on_ft = ['c', 'cpp']

[[plugins]]
repo='https://github.com/matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/kuuote/ddc-source-yank'
on_source = 'ddc.vim'
hook_add = '''
  nnoremap cy <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
  xnoremap Y <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
'''

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-matcher_vimregexp'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-matcher_prefix'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-sorter_head'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo='https://github.com/Shougo/ddc-filter-converter_truncate_abbr'
on_source = 'ddc.vim'
