[[plugins]]
repo='https://github.com/Shougo/ddu.vim'
hooks_file='~/dotfiles/config/nvim/rc/ddu.vim'
lua_source='''
   vim.fn['ddu#custom#patch_local']('file_recursive', {
     ui = 'ff',
     uiParams = {
       ff = {
         filterFloatingPosition = 'bottom',
         filterSplitDirection = 'floating',
         floatingBorder = 'rounded',
         previewFloating = true,
         previewFloatingBorder = 'rounded',
         previewFloatingTitle = 'Preview',
         previewSplit = 'horizontal',
         prompt = '> ',
         split = 'floating',
         startFilter = true,
       },
     },
     sources = {
       {
         name = { 'file_rec' },
         options = {
           matchers = {
             'matcher_substring',
           },
           converters = {
             'converter_devicon',
             'converter_hl_dir',
           },
           ignoreCase = true,
         },
         params = {
           ignoredDirectories = { 'node_modules', '.git', '.vscode' },
         },
       },
     },
     kindOptions = {
       file = {
         defaultAction = 'open',
       },
     },
     filterParams = {
       converter_hl_dir = {
         hlGoup = {"Directory", "Keyword"},
       },
     },
   })

   vim.fn['ddu#custom#patch_local']('colorscheme', {
     ui = 'ff',
     sources = {
       {
         name = { 'colorscheme' },
         options = {
           matchers = {
             'matcher_substring',
           },
           ignoreCase = true,
         },
       },
     },
     kindOptions = {
       colorscheme = {
         defaultAction = 'set',
       },
     },
   })

   vim.fn['ddu#custom#patch_local']('buffer_list', {
     ui = 'ff',
     uiParams = {
       ff = {
         filterFloatingPosition = 'top',
         filterSplitDirection = 'floating',
         floatingBorder = 'rounded',
         prompt = 'buffer > ',
         split = 'floating',
       },
     },
     sources = {
       {
         name = { 'buffer' },
         options = {
           matchers = {
             'matcher_substring',
           },
           converters = {
             'converter_devicon',
             'converter_hl_dir',
           },
           ignoreCase = true,
         },
       },
     },
     kindOptions = {
       file = {
         defaultAction = 'open',
       },
     },
     filterParams = {
       converter_hl_dir = {
         hlGoup = {"Directory", "Keyword"},
       },
     },
   })
'''

[[plugins]]
repo='https://github.com/lambdalisue/kensaku.vim'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
[[plugins]]
on_source = 'ddu.vim'
repo='https://github.com/lambdalisue/mr.vim'
#------------------------------
#-- | ui                       |
#------------------------------
[[plugins]]
repo='https://github.com/Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hooks_file='~/dotfiles/config/nvim/rc/ddu-ui-ff.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hooks_file='~/dotfiles/config/nvim/rc/ddu-ui-filer.vim'
#------------------------------
#-- | column                   |
#------------------------------
[[plugins]]
repo='https://github.com/Shougo/ddu-column-filename'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/tamago3keran/ddu-column-devicon_filename'
on_source = 'ddu.vim'
#------------------------------
#-- | filter                   |
#------------------------------
[[plugins]]
repo='https://github.com/Milly/ddu-filter-kensaku'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_ignore_files'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_ignores'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_files'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-sorter_alpha'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-sorter_reversed'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kamecha/ddu-filter-converter_file_icon'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kamecha/ddu-filter-converter_file_info'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/uga-rosa/ddu-filter-converter_devicon'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'
#------------------------------
#-- | kind                     |
#------------------------------
[[plugins]]
repo='https://github.com/Shougo/ddu-kind-file'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-kind-word'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/4513ECHO/ddu-kind-url'
on_source = 'ddu.vim'
#------------------------------
#-- | source                   |
#------------------------------
[[plugins]]
repo='https://github.com/Shougo/ddu-source-output'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-path_history'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-action'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-register'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-file_point'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/4513ECHO/ddu-source-colorscheme'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/4513ECHO/ddu-source-emoji'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-dummy'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-file'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-file_old'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/Shougo/ddu-source-line'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kuuote/ddu-source-git_diff'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kuuote/ddu-source-git_status'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kuuote/ddu-source-mr'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-source-command'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-source-git_branch'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-source-git_diff_tree'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-source-git_log'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kyoh86/ddu-source-lazy_nvim'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/matsui54/ddu-source-command_history'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/matsui54/ddu-source-file_external'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/matsui54/ddu-source-help'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/peacock0803sz/ddu-source-git_stash'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/shun/ddu-source-buffer'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/shun/ddu-source-rg'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'
hook_add = '''
  " Jump to definition
  nnoremap td <Cmd>call ddu#start(#{
        \   sync: v:true,
        \   sources: [
        \     #{
        \       name: 'lsp_definition',
        \     },
        \   ],
        \   uiParams: #{
        \     ff: #{
        \       ignoreEmpty: v:true,
        \       immediateAction: 'open',
        \     },
        \   },
        \ })<CR>
'''
[[plugins]]
repo='https://github.com/uga-rosa/ddu-source-search_history'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/mikanIchinose/ddu-source-markdown'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'
[[plugins]]
repo='https://github.com/yuki-yano/ddu-source-nvim-notify'
on_source = 'ddu.vim'
