[[plugins]]
repo='https://github.com/kuuote/dotvim'
if=false
name='kuuote_dotfiles'

[[plugins]]
repo='https://github.com/Shougo/shougo-s-github'
if=false
name='shougo_dotfiles'

[[plugins]]
repo='https://github.com/keimoriyama/.dotfiles'
if=false
name='keimoriyama_dotfiles'

[[plugins]]
repo='https://github.com/Warashi/dotfiles'
if=false
name='warashi_dotfiles'

[[plugins]]
repo='https://github.com/yasunori0418/dotfiles'
if=false
name='yasunori0418_dotfiles'

[[plugins]]
repo='https://github.com/i9wa4/dotfiles'
if=false
name='i9wa4_dotfiles'

[[plugins]]
repo='https://github.com/kg8m/dotfiles'
if=false
name='kg8m_dotfiles'

[[plugins]]
repo='https://github.com/raa0121/dotfiles'
if=false
name='raa0121_dotfiles'

[[plugins]]
repo='https://github.com/gamoutatsumi/dotfiles'
if=false
name='gamoutatsumi_dotfiles'

[[plugins]]
repo='https://github.com/NI57721/dotfiles'
if=false
name='NI57721_dotfiles'

[[plugins]]
repo='https://github.com/kawarimidoll/dotfiles'
if=false
name='kawarimidoll_dotfiles'

[[plugins]]
repo='https://github.com/sevenc-nanashi/dotfiles'
if=false
name='sevenc-nanashi_dotfiles'

[[plugins]]
repo='https://github.com/utubo/dotfiles'
if=false
name='utubo_dotfiles'

[[plugins]]
repo='https://github.com/stevearc/dotfiles'
if=false
name='stevearc_dotfiles'

[[plugins]]
repo='https://github.com/monaqa/dotfiles'
if=false
name='monaqa_dotfiles'

[[plugins]]
repo='https://github.com/yutkat/dotfiles'
if=false
name='yutkat_dotfiles'

[[plugins]]
repo='https://github.com/LumaKernel/dotfiles'
if=false
name='LumaKernel_dotfiles'

[[plugins]]
repo='https://github.com/skanehira/dotfiles'
if=false
name='skanehira_dotfiles'

[[plugins]]
repo='https://github.com/uga-rosa/dotfiles'
if=false
name='uga-rosa_dotfiles'

[[plugins]]
repo='https://github.com/atusy/dotfiles'
if=false
name='atusy_dotfiles'
