[[plugins]]
repo = 'https://github.com/Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-lazy'
on_source = 'dpp.vim'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-toml'
on_source = 'dpp.vim'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-local'
on_source = 'dpp.vim'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-packspec'
on_source = 'dpp.vim'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

