[[plugins]]
repo='https://github.com/lambdalisue/fern.vim'
lua_source ='''
vim.g["fern#default_hidden"] = 1
vim.g["fern#renderer"] = "nerdfont"
vim.g["fern#renderer#nerdfont#indent_markers"] = 1

local opts = { noremap = true, silent = true }
local keymap = vim.keymap.set
keymap({ "n" }, "<Leader>f", "<Cmd>Fern .<Cr>", opts)
keymap({ "n" }, "<Leader>F", "<Cmd>Fern %:h<Cr>", opts)
keymap({ "n" }, "<C-f>", "<Cmd>Fern . -reveal=%<Cr>", opts)

local autocmd = require("utils").autocmd
autocmd(
  { "FileType"},
  {
    pattern = "fern",
    callback = function()
      local buffer_silent = { silent =true, buffer = true }
      vim.opt_local.signcolumn="no"
      vim.opt_local.number=false

      vim.keymap.set("n", "<C-m>", "<Plug>(fern-action-move)", buffer_silent)
      vim.keymap.set("n", "<C-s>", "<Plug>(fern-action-new-dir)", buffer_silent)
      vim.keymap.set("n", "<Leader>cd", "<Plug>(fern-action-cd:cursor)", buffer_silent)
      vim.keymap.set("n", "p", "<Plug>(fern-action-preview:auto:toggle)", buffer_silent)
      vim.keymap.set("n", "<C-n>", "<Plug>(fern-action-preview:scroll:down:half)", buffer_silent)
      vim.keymap.set("n", "<C-p>", "<Plug>(fern-action-preview:scroll:up:half)", buffer_silent)
      vim.keymap.set("n", "g.", "<Plug>(fern-action-hidden:toggle)", buffer_silent)
      vim.keymap.set("n", "-", "<Plug>(fern-action-leave)", buffer_silent)
    end,
  }
)
'''

[[plugins]]
repo='https://github.com/lambdalisue/fern-git-status.vim'
depends = 'fern.vim'

[[plugins]]
repo='https://github.com/lambdalisue/fern-renderer-nerdfont.vim'
depends = 'fern.vim'

[[plugins]]
repo='https://github.com/lambdalisue/nerdfont.vim'
depends = 'fern.vim'

[[plugins]]
repo='https://github.com/yuki-yano/fern-preview.vim'
depends = 'fern.vim'

