[[plugins]]
repo = 'https://github.com/lambdalisue/gin.vim'
on_cmd = [
  'Gin',
]
lua_source ='''
local autocmd = require('utils').autocmd
local abbrev = require('utils').make_abbrev

autocmd({ 'FileType' }, {
  pattern = { 'gin-diff', 'gin-log', 'gin-status' },
  callback = function()
    local keymap = vim.keymap.set
    local opts = { buffer = true, noremap = true }
    keymap({ 'n' }, 'c', '<Cmd>Gin commit<Cr>', opts)
    keymap({ 'n' }, 's', '<Cmd>GinStatus<Cr>', opts)
    keymap({ 'n' }, 'L', '<Cmd>GinLog --graph --oneline<Cr>', opts)
    keymap({ 'n' }, 'd', '<Cmd>GinDiff --cached<Cr>', opts)
    keymap({ 'n' }, 'q', '<Cmd>bdelete<Cr>', opts)
    keymap({ 'n' }, 'p', [[<Cmd>lua vim.notify("Gin push")<Cr><Cmd>Gin push<Cr>]], opts)
    keymap({ 'n' }, 'P', [[<Cmd>lua vim.notify("Gin pull")<Cr><Cmd>Gin pull<Cr>]], opts)
  end,
})

autocmd({ 'FileType' }, {
  pattern = 'gin-diff',
  callback = function()
    local keymap = vim.keymap.set
    keymap(
      { 'n' },
      'gd',
      '<Plug>(gin-diffjump-smart)<Cmd>lua vim.lsp.buf.definition()<CR>',
      { buffer = true, silent = true }
    )
  end,
})

autocmd({ 'FileType' }, {
  pattern = 'gin-status',
  callback = function()
    local keymap = vim.keymap.set
    local opts = { buffer = true, noremap = true }
    keymap({ 'n' }, 'h', '<Plug>(gin-action-stage)', opts)
    keymap({ 'n' }, 'l', '<Plug>(gin-action-unstage)', opts)
  end,
})

abbrev {
  { from = 'gb', to = 'GinBranch' },
  { from = 'gc', to = 'Gin commit' },
  { from = 'gca', to = 'Gin commit --amend' },
  { from = 'gd', to = 'GinDiff' },
  { from = 'gds', to = 'GinDiff --cached' },
  { from = 'gin', to = 'Gin' },
  { from = 'git', to = 'Gin' },
  { from = 'gl', to = 'GinLog --graph --oneline' },
  { from = 'gp', to = 'Gin push' },
  { from = 'gpp', to = 'Gin pull' },
  { from = 'gs', to = 'GinStatus' },
  { from = 'gcd', to = 'GinCd' },
}

abbrev {
  { prepose = 'Gin commit', from = 'a', to = '--amend' },
}

vim.keymap.set({ 'n' }, '<C-g><C-s>', '<Cmd>GinStatus<Cr>', {})
vim.keymap.set({ 'n' }, '<C-g><C-l>', '<Cmd>GinLog --graph --oneline<Cr>', {})
vim.keymap.set({ 'n' }, '<C-g><C-b>', '<Cmd>GinBranch<Cr>', {})
'''
