[[plugins]]
repo='https://github.com/lewis6991/gitsigns.nvim'
on_event='BufReadPost'
lua_source='''
local gitsigns = require('gitsigns')
gitsigns.setup {
  signcolumn = true,
  numhl = true,
  attach_to_untracked = true,
}

local opts = { noremap = true, silent = true }
local keymap = vim.keymap.set
keymap('n', '[g', function()
  gitsigns.prev_hunk()
end, opts)
keymap('n', ']g', function()
  gitsigns.next_hunk()
end, opts)
keymap('n', '<C-g><C-p>', function()
  gitsigns.preview_hunk()
end, opts)
keymap({ 'n', 'x' }, '<C-g><C-a>', function()
  gitsigns.stage_hunk()
end, opts)
keymap('n', '<C-g><C-r>', function()
  gitsigns.undo_stage_hunk()
end, opts)
keymap('n', '<C-g><C-q>', function()
  gitsigns.setqflist()
end, opts)
keymap('n', '<C-g><C-v>', function()
  gitsigns.blame_line()
end, opts)
'''
