[[plugins]]
repo='https://git.sr.ht/~whynothugo/lsp_lines.nvim'
lua_source='''
require("lsp_lines").setup()

vim.diagnostic.config({
  virtual_text = false,
  update_in_insert = true,
})
vim.keymap.set(
  "n",
  "<Leader>ll",
  require("lsp_lines").toggle,
  { desc = "Toggle lsp_lines", silent = true }
)
'''
