[[plugins]]
repo='https://github.com/potamides/pantran.nvim'
lua_source='''
local pantran = require("pantran")
vim.env.DEEPL_AUTH_KEY = require("local_vimrc").DEEPL_AUTHKEY

local opts = {noremap = true, silent = true, expr = true}
local keymap = vim.keymap.set
keymap("n", "<leader>tr", pantran.motion_translate, opts)
keymap("n", "<leader>trr", function() return pantran.motion_translate() .. "_" end, opts)
keymap("x", "<leader>tr", pantran.motion_translate, opts)

pantran.setup({
    default_engine = "deepl",
    engines = {
      deepl = {
        default_target = "JA"
      },
    },
    controls = {
      mappings = {
        edit = {
          n = {
            ["j"] = "gj",
            ["k"] = "gk"
          },
          i = {
            ["<C-y>"] = false,
            ["<C-a>"] = require("pantran.ui.actions").yank_close_translation
          }
        },
      }
    }
  })
'''
